# Numpy exercices pratiques
Ce notebook à pour objectif de vous faire pratiquer numpy dans toute sa généralité. 
Vous avez donc une liste de questions à faire ! Il ne faut pas hésiter à faire des recherches sur google ainsi que voir la [documentation officielle](https://docs.scipy.org/doc/numpy-1.13.0/reference/). 

#### Q1 : Importer le package numpy 

In [76]:
import numpy as np

#### Q2 : Afficher la version de numpy et la configuration 

In [77]:
print(np.__version__)
print(np.show_config())

1.19.5
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
None


#### Q3 : Créer un vecteur nul de taille 10

In [5]:
x = np.zeros(10)
print(x)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### Q4 : Créer un vecteur null de taille 10 et affecter la valeur 1 à la 4ème place (index 4) du vecteur

In [6]:
x[4] = 1
print(x)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### Q5 : Créer un vecteur Z de 40 valeurs allant de 10 à 50 

In [9]:
z = np.arange( 10, 51 )
print(z)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]


#### Q6 : Inverser Z (le premier élément devient donc le dernier)

In [11]:
print(np.flip(z))

[50 49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27
 26 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


#### Q7 : Créer une matrice 3x3 avec des valeurs comprise entre 0 et 8 

In [12]:
x =  np.arange(0, 9).reshape(3,3)
print(x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### Q8 : Créer une matrice identié 3x3 

In [19]:
x = np.eye(3,3)
print(x)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### Q9 : Créer une matrice 3x3x3 avec des valeurs random 

In [14]:
x = np.random.random((3,3,3))
print(x)

[[[0.43858917 0.08272452 0.22132359]
  [0.32401315 0.4839723  0.44344582]
  [0.56759496 0.05188976 0.17828837]]

 [[0.82258135 0.43932844 0.73044336]
  [0.92582813 0.56125469 0.60360722]
  [0.29868021 0.67764415 0.85708992]]

 [[0.51149208 0.8973161  0.48677976]
  [0.82950171 0.80017995 0.5021838 ]
  [0.824593   0.62048115 0.34556405]]]


#### Q10 : Créer une matrice 10x10 avec des valeurs random et afficher le minimum et maximum de cette matrice

In [27]:
x = np.random.random((10,10))
print(x)
print(x.min())
print(x.min())

[[0.74757485 0.17223644 0.67325558 0.50715947 0.57176529 0.92779578
  0.14926912 0.52136918 0.76175572 0.45730269]
 [0.52155562 0.07117433 0.99309344 0.90344989 0.46783208 0.80332611
  0.58835071 0.43247024 0.94076053 0.7966429 ]
 [0.20519206 0.74722326 0.70972821 0.62378879 0.80748122 0.46019262
  0.98029707 0.38565426 0.57685841 0.32252067]
 [0.64811574 0.8131831  0.9728594  0.57894341 0.33827889 0.15439267
  0.09108405 0.81001138 0.97940503 0.67137144]
 [0.40966501 0.29407141 0.76441864 0.03393216 0.08125117 0.99364222
  0.49874073 0.73207314 0.50844272 0.36517232]
 [0.04486723 0.24053099 0.89676644 0.83169245 0.39674135 0.49103708
  0.83117103 0.37492959 0.94438904 0.67600581]
 [0.14626679 0.13676716 0.23005247 0.73199232 0.05691939 0.4199302
  0.4481749  0.8295033  0.24800661 0.38594071]
 [0.12405535 0.66728129 0.79140689 0.98903118 0.35697682 0.13271341
  0.34168895 0.27044272 0.38630893 0.76361073]
 [0.41233161 0.9835426  0.32352709 0.08183115 0.23132174 0.28720366
  0.46388841 

#### Q11 : Créer une matrice 5x5 avec les valeurs 1,2,3,4 en dessous de la diagonale 

In [35]:
x = np.array([1,2,3,4])
print(np.diag(x,-1))

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


 Q12 : Créer une liste random de taille 5 et donner la somme de ses éléments  

In [24]:
x  = np.random.random((5))
print(np.sum(x))

2.0499340762198446


#### Q13 : Créer une liste random de taille 5 et donner la moyenne de ses éléments

In [33]:
x  = np.random.random((5))
print(np.mean(x))

0.48735752176584224


#### Q14 : En utilisant une fonction, donner la taille de la liste suivante :
```python 
l = [x for x in range(11)]
```

In [40]:
l = [x for x in range(11)]
print(np.size(l))

11


#### Q15 : Créer un tableau de taille 10 avec des valeurs comprises entre 0 et 1 EXCLUS 

In [83]:
x = np.random.ranf(10)
print(x)

[0.75929788 0.16720854 0.79346041 0.90028575 0.83718944 0.01364091
 0.16866047 0.19375761 0.69399704 0.21786599]


#### Q16 : Soit deux tableau A et B de dimension 1 et de taille 5, créer A et B et afficher True si A et B sont égaux False sinon

In [52]:
a = np.array([1,2,2,4,5])
print(a)
b = np.array([1,2,3,4,5])
print(b)
np.array_equal(a,b)

[1 2 2 4 5]
[1 2 3 4 5]


False

#### Q17 : Convertir un tableau de float32 de dimension 1 et de taille 10 en un tableau de meme taille et dimension mais de type int32

In [50]:
 x = np.arange(10, dtype=np.float32)
print(x)
x.astype(int)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

#### Q18 : Normaliser une matrice random 5x5 
La normalisation d'un nombre X consiste à lui retirer sa moyenne et a diviser le tout par son écart type 

In [75]:
x= np.random.random((5,5))
x = (x - x.mean())/(np.std(x))
print(x)

[[ 0.97208999  0.20198039 -0.2338589   0.51694085  0.5212536 ]
 [-0.66195766 -1.77852885  0.02269434  1.21764062 -1.47046653]
 [-0.59090686  0.31121094  0.05782146  0.58499131 -1.09878173]
 [ 1.46876601 -1.17050702  1.3484527   1.45099693 -1.40495952]
 [ 0.71282987  0.94049923 -1.64977026  0.41328242 -0.68171333]]


#### Q19 : Créer une matrice random `M` 2x2 et donner sa transposer 
L'opération de transposition dans une matrice consiste à échanger les lignes et le colonnes. 

In [57]:
m = np.random.random((2,2))
print(m)
np.transpose(m)

[[0.97917914 0.31981324]
 [0.63143027 0.42223222]]


array([[0.97917914, 0.63143027],
       [0.31981324, 0.42223222]])

#### Q20 : Écrire un petit script qui remplace un élément au hasard dans une matrice de dimension NxN

In [61]:
a = 3
b = 3
x = np.eye(a,b)


SyntaxError: invalid syntax (<ipython-input-61-dc7eae1517ab>, line 4)

#### Q21 : Considérons une matrice de dimension (5,5,3), écrire un script qui multiplie cette matrice par une matrice de dimension (5,5)

In [72]:
a = np.eye(5,5,3)
def multiply(a):
    b = np.eye(5,5)
    return a*b

print(multiply(a))

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
