# Numpy exercices pratiques
Ce notebook à pour objectif de vous faire pratiquer numpy dans toute sa généralité. 
Vous avez donc une liste de questions à faire ! Il ne faut pas hésiter à faire des recherches sur google ainsi que voir la [documentation officielle](https://docs.scipy.org/doc/numpy-1.13.0/reference/). 

#### Q1 : Importer le package numpy 

In [1]:
import numpy as np

#### Q2 : Afficher la version de numpy et la configuration 

In [4]:
print(np.__version__)
print(np.show_config())

1.19.5
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
None


#### Q3 : Créer un vecteur nul de taille 10

In [5]:
x = np.zeros(10)
print(x)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### Q4 : Créer un vecteur null de taille 10 et affecter la valeur 1 à la 4ème place (index 4) du vecteur

In [6]:
x[4] = 1
print(x)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### Q5 : Créer un vecteur Z de 40 valeurs allant de 10 à 50 

In [9]:
z = np.arange( 10, 51 )
print(z)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]


#### Q6 : Inverser Z (le premier élément devient donc le dernier)

In [11]:
print(np.flip(z))

[50 49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27
 26 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


#### Q7 : Créer une matrice 3x3 avec des valeurs comprise entre 0 et 8 

In [12]:
x =  np.arange(0, 9).reshape(3,3)
print(x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### Q8 : Créer une matrice identié 3x3 

In [19]:
x = np.eye(3,3)
print(x)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### Q9 : Créer une matrice 3x3x3 avec des valeurs random 

In [14]:
x = np.random.random((3,3,3))
print(x)

[[[0.43858917 0.08272452 0.22132359]
  [0.32401315 0.4839723  0.44344582]
  [0.56759496 0.05188976 0.17828837]]

 [[0.82258135 0.43932844 0.73044336]
  [0.92582813 0.56125469 0.60360722]
  [0.29868021 0.67764415 0.85708992]]

 [[0.51149208 0.8973161  0.48677976]
  [0.82950171 0.80017995 0.5021838 ]
  [0.824593   0.62048115 0.34556405]]]


#### Q10 : Créer une matrice 10x10 avec des valeurs random et afficher le minimum et maximum de cette matrice

In [18]:
x = np.random.random((10,10))
print(x)
print(x.min())
print(x.max())

[[0.4580563  0.54420219 0.99135679 0.1730876  0.76118844 0.49848837
  0.51351888 0.86182871 0.62436761 0.38984931]
 [0.29223625 0.58034707 0.1703678  0.050035   0.06426365 0.61967681
  0.04190872 0.1279027  0.97310862 0.11464684]
 [0.65771671 0.78538532 0.59085102 0.52112228 0.14012668 0.07852575
  0.87081973 0.38495918 0.52051598 0.53594394]
 [0.539028   0.2050726  0.68346957 0.59040668 0.13319438 0.62335395
  0.12620014 0.64768187 0.82386255 0.22741548]
 [0.05878104 0.91503831 0.88876989 0.74227167 0.24626064 0.46113332
  0.7309439  0.24121529 0.11144679 0.53365684]
 [0.41800271 0.96639912 0.54134176 0.62847989 0.35784444 0.1719245
  0.03489395 0.25280357 0.63802497 0.76314981]
 [0.80129215 0.36022284 0.82745208 0.14965812 0.64591654 0.74651164
  0.01884449 0.86660324 0.99270512 0.23838161]
 [0.76387098 0.01801034 0.94456367 0.33465425 0.46861328 0.68771287
  0.92790013 0.23347226 0.77105578 0.02288344]
 [0.40041438 0.38693768 0.86783086 0.32165464 0.47746631 0.84669035
  0.25683275 

#### Q11 : Créer une matrice 5x5 avec les valeurs 1,2,3,4 en dessous de la diagonale 

#### Q12 : Créer une liste random de taille 5 et donner la somme de ses éléments  

#### Q13 : Créer une liste random de taille 5 et donner la moyenne de ses éléments

#### Q14 : En utilisant une fonction, donner la taille de la liste suivante :
```python 
l = [x for x in range(11)]
```

#### Q15 : Créer un tableau de taille 10 avec des valeurs comprises entre 0 et 1 EXCLUS 

#### Q16 : Soit deux tableau A et B de dimension 1 et de taille 5, créer A et B et afficher True si A et B sont égaux False sinon

#### Q17 : Convertir un tableau de float32 de dimension 1 et de taille 10 en un tableau de meme taille et dimension mais de type int32

#### Q18 : Normaliser une matrice random 5x5 
La normalisation d'un nombre X consiste à lui retirer sa moyenne et a diviser le tout par son écart type 

#### Q19 : Créer une matrice random `M` 2x2 et donner sa transposer 
L'opération de transposition dans une matrice consiste à échanger les lignes et le colonnes. 

#### Q20 : Écrire un petit script qui remplace un élément au hasard dans une matrice de dimension NxN

#### Q21 : Considérons une matrice de dimension (5,5,3), écrire un script qui multiplie cette matrice par une matrice de dimension (5,5)